export default [
    {
        // Vendored/minified files — skip entirely
        ignores: [
            "js/jscrossword/**",
            "js/c3.min.js",
            "js/d3.v3.min.js",
        ],
    },
    {
        files: ["js/**/*.js"],
        languageOptions: {
            globals: {
                // Browser
                window: "readonly",
                document: "readonly",
                console: "readonly",
                navigator: "readonly",
                alert: "readonly",
                FileReader: "readonly",
                Blob: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                Uint8Array: "readonly",
                Set: "readonly",
                parseInt: "readonly",
                parseFloat: "readonly",
                isNaN: "readonly",
                Number: "readonly",
                String: "readonly",
                Math: "readonly",
                JSON: "readonly",
                Array: "readonly",
                Object: "readonly",
                Boolean: "readonly",
                Date: "readonly",
                RegExp: "readonly",
                Error: "readonly",
                Promise: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",

                // CDN libraries
                Chart: "readonly",
                JSCrossword: "readonly",

                // Cross-file project globals (defined in one .js, used in another or in index.html)
                init: "readonly",
                render_all: "readonly",
                render_grid: "readonly",
                render_clues: "readonly",
                render_entries: "readonly",
                render_theme: "readonly",
                render_metadata: "readonly",
                entries_of_length: "readonly",
                clues_of_length: "readonly",
                toggle_theme: "readonly",
                toggleById: "readonly",
                toggleByClass: "readonly",
                sort_entries: "readonly",
                display_grid: "readonly",
                letter_frequency: "readonly",
                highlighted_letters: "readonly",
                standard_letter_distribution: "readonly",
                ALPHABET: "readonly",
                grid_render_to: "readonly",
                clues_render_to: "readonly",
                entries_render_to: "readonly",
                tabLinks: "readonly",
                contentDivs: "readonly",
                puzdata: "readonly",
            },
        },
        rules: {
            "no-unused-vars": "warn",
            "no-redeclare": "warn",
            "eqeqeq": "warn",
        },
    },
];
